### ISSUE TITLE
Opening/Closing Bad Ion File Has Persistent "Problems"

### ISSUE THREAD

**Issue by almann** [amzn/ion-vscode-plugin#68]
When opening an Ion file with errors outside of a workspace, then closing it, the "problems" remain.  Not sure if this works as designed, or a bug.

1. Open a new window.
2. Open a file with bad Ion.
3. Close the file.

Doing this causes the "problems" of the now closed file to remain.  This seems wrong to me--but it could be a misunderstanding on my part around VS Code's model.

![image](https://user-images.githubusercontent.com/503506/90662764-a043e100-e1fd-11ea-9734-65f744b231e7.png)

**Comment by therapon** [comment]
Tried the same steps for a JSON file. The problems tab is cleared when the faulting JSON file is closed.
