### ISSUE TITLE
Missing Completion Method 

### ISSUE THREAD

**Issue by lziq** [amzn/ion-vscode-plugin#78]
When typing in the editor, completion request failure keeps popping up in the information window, until the file is complete. 

![Screen Shot 2020-08-27 at 9 06 36 PM](https://user-images.githubusercontent.com/67429381/91513260-88c5c180-e8a9-11ea-8476-bbe3cb61122d.png)

**Comment by lziq** [comment]
You can simply add `connection.onCompletion ((_textDocumentPosition) => {return []});` in 'server.ts' file to fix this bug.

**Comment by MFornander** [comment]
This bug makes the extension almost unusable since the output window keeps having these errors when typing new ion.
