### ISSUE TITLE
 Request textDocument/completion failed

### ISSUE THREAD

**Issue by Phrogz** [amzn/ion-vscode-plugin#80]
Steps to reproduce:

1. Create a document like this, using the ion language.

```ion
$ion_schema_1_0

type::{
  name: LimeStylesheet,
  type: struct,
  // NOTE: implicitly content:open, allows additional field types to be added and sent
  fields: {
    variables: {
      type: struct,
      occurs: required,
    },
  }
}
```

2. Select the text `variables` and type the letter `v`.

**EXPECTED**: No errors.  
**ACTUAL**: Language Server gives the following warning, with an associated toast/notification showing up.

```
[Error - 11:00:38 AM] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
```

Using `ion-extension` v0.2.0 on  
```
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by ringohoffman** [comment]
I have been having similar issues. With @Phrogz 's example, I'm only able to recreate this with the version currently available for download through the marketplace. When I clone the latest commit on this repo and build it, the error does not occur.

The last time the extension was updated on the marketplace was 8/13/2020 (1 year and 7 months). Is it possible to release a new build? @lziq @therapon

**Comment by therapon** [comment]
Unfortunately I no longer have access to the account credentials to perform a re-publish. The credentials are owned/managed by the team inside Amazon. @lziq might be able to help.

**Comment by lziq** [comment]
It seems I need to log in the publisher "TheIonTeam" to get it published again. However, it requires a personal access token, and I already forgot it. @therapon Can you log in the Visual Studio Marketplace publisher [management page](https://marketplace.visualstudio.com/manage) and in the publisher "TheIonTeam", add me as an owner, so I can see if I am able to create a new PAT?

**Comment by lziq** [comment]
Followup on my previous comment, sorry I think I got these credentials in a document.

**Comment by lziq** [comment]
I updated the extension in market place with the fix on this PR https://github.com/amzn/ion-vscode-plugin/pull/83. Now I think this problem is resolved.
